name: Release

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version'
        required: true
      release_notes:
        description: 'Release notes'
        required: false
        default: ''

  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Decode Keystore
        run: echo "${{ secrets.SIGNING_KEYSTORE_BASE64 }}" | base64 --decode > app/release-key.jks

      - name: Build with Gradle
        run: bash ./gradlew clean assembleRelease
        env:
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}

      - name: Rename APK with version
        run: mv ./app/build/outputs/apk/release/app-release.apk ./app/build/outputs/apk/release/sms-relay-${{ github.event.inputs.release_version != '' && github.event.inputs.release_version || github.ref_name }}.apk

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.release_version || github.ref_name }}
          name: Release ${{ github.event.inputs.release_version || github.ref_name }}
          body: ${{ github.event.inputs.release_notes || '' }}
          files: ./app/build/outputs/apk/release/sms-relay-${{ github.event.inputs.release_version || github.ref_name }}.apk
